-- 코드를 작성해주세요
-- 3세대의 대장균 ID
-- 분화 2번 (+2+2)
SELECT ID 
FROM ECOLI_DATA 
WHERE PARENT_ID IN (
    SELECT ID
    FROM ECOLI_DATA
        WHERE PARENT_ID IN (
             SELECT ID
             FROM ECOLI_DATA
             WHERE PARENT_ID IS NULL
        )
)
ORDER BY ID

-- JOIN으로 풀이 가능함

-- SELECT F.ID
-- FROM ECOLIDATA AS F JOIN ECOLIDATA AS S 
-- ON F.PARENTID = S.ID
-- JOIN ECOLIDATA AS T 
-- ON S.PARENTID = T.ID
-- WHERE T.PARENTID IS NULL
-- ORDER BY F.ID ASC;