-- 코드를 작성해주세요   

SELECT SUM(CASE WHEN LENGTH IS NULL THEN 1 END) AS FISH_COUNT
FROM FISH_INFO
-- 10CM 이하는 NULL
WHERE LENGTH IS NULL

# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO
# -- 10CM 이하는 NULL
# WHERE LENGTH IS NULL

# SELECT COUNT(*)-COUNT(LENGTH) AS FISH_COUNT
# FROM FISH_INFO
# -- 10CM 이하는 NULL
# WHERE LENGTH IS NULL

# SELECT COUNT(LENGTH IS NULL) AS FISH_COUNT
# FROM FISH_INFO
# WHERE LENGTH IS NULL = 1

# SQL 조회시 속도가 느린 점이 걸리는데 어떻게 데이터를 조회하면 좀더 빠르게 나올지 고민해보기