-- 코드를 입력하세요
SELECT A_OUTS.ANIMAL_ID, A_OUTS.NAME
FROM ANIMAL_INS AS A_INS JOIN ANIMAL_OUTS AS A_OUTS
ON A_INS.ANIMAL_ID = A_OUTS.ANIMAL_ID
-- 보호 기간이 긴 순으로 조회
ORDER BY DATEDIFF(A_OUTS.DATETIME, A_INS.DATETIME) DESC
LIMIT 2