-- 코드를 입력하세요
-- '세단'|'SUV' 2022.11.01-2022.11.30 / 50~200
-- fee : 30일 이용 * 할인
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR AS C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE
-- WHERE START_DATE - END_DATE / 렌탈 기록에 없는 CAR_ID / 30일 할인
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE END_DATE >= '2022-11-01' AND START_dATE <= '2022-12-01'
) AND DURATION_TYPE LIKE '30%'
GROUP BY CAR_ID
-- 50~200
HAVING CAR_TYPE IN ('세단','SUV') AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC