-- 0% ~ 25% = 'CRITICAL'
-- 26% ~ 50% = 'HIGH'
-- 51% ~ 75% = 'MEDIUM'
-- 76% ~ 100% =  'LOW' 
-- NTILE : 데이터를 정렬, 지정된 수의 동일한 크기로 분할
SELECT ID, CASE
     WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
     WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
     WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
     WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 4 THEN 'LOW'
     END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;