-- 코드를 입력하세요
-- 조회
-- 조건 : 대여 기간이 30일 이상 = 장기대여, ELSE 단기대여
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,'%Y-%m-%d') AS START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE, 
CASE WHEN DATEDIFF(END_DATE, START_DATE) < 29 THEN "단기 대여"
    ELSE "장기 대여" END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- 조건 : 2022년 9월 1월- 30일 사이 대여 시작일
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC
