-- 코드를 입력하세요
-- 보호소에 들어온 기록이 없는 동물
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS AS OUTS LEFT JOIN ANIMAL_INS AS INS 
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL 
ORDER BY OUTS.ANIMAL_ID ASC
