-- 코드를 입력하세요
-- 2021 가입 회원 중 상품을 구매한 회원수(반올림- 분자)와 전체 회원의 비율(분모)을 년/월 출별
SELECT DATE_FORMAT(S.SALES_DATE, '%Y') AS YEAR, 
        DATE_FORMAT(S.SALES_DATE, '%m') AS MONTH, 
COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS
, ROUND(COUNT(DISTINCT U.USER_ID)
        /(SELECT COUNT(*) FROM USER_INFO
          WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO AS U JOIN ONLINE_SALE AS S
ON U.USER_ID = S.USER_ID 
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH 