-- 코드를 입력하세요
-- ANIMAL_ID = 키 코드
SELECT A_INS.NAME, A_INS.DATETIME
FROM ANIMAL_INS AS A_INS LEFT JOIN ANIMAL_OUTS AS A_OUTS
ON A_INS.ANIMAL_ID = A_OUTS.ANIMAL_ID
-- 가장 오래 보호소에 있던. 보호 시작일 순 조회 / 입양보낸 테이블 = ANIMAL_OUTS
WHERE A_OUTS.ANIMAL_ID IS NULL
ORDER BY A_INS.DATETIME
LIMIT 3