-- 코드를 입력하세요
-- APNT_NO PT_NAME	PT_NO MCDP_CD DR_NAME APNT_YMD
-- 2022.04.13 CS 진료 예약 내역
SELECT A.APNT_NO, P.PT_NAME,A.PT_NO,A.MCDP_CD,DR_NAME,A.APNT_YMD
FROM APPOINTMENT A JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
JOIN  PATIENT AS P
ON A.PT_NO = P.PT_NO
WHERE A.APNT_CNCL_YMD IS NULL AND A.MCDP_CD LIKE "CS" AND A.APNT_YMD LIKE "2022-04-13%"
ORDER BY A.APNT_YMD ASC