-- 코드를 입력하세요
-- 3월 생일자 여성 회원 
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m%-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
-- 3월 생일
WHERE (MONTH(DATE_OF_BIRTH) = 3) 
AND (GENDER='W') 
AND (TLNO IS NOT NULL)
ORDER BY MEMBER_ID ASC