-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP JOIN REST_REVIEW AS R
ON MP.MEMBER_ID = R.MEMBER_ID
-- 리뷰를 가장 많이 작성한 회원 
WHERE MP.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT 