-- 코드를 작성해주세요
--  부모의 형질을 모두 보유하고 있는 대장균
SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
-- () AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C, ECOLI_DATA AS P
WHERE C.PARENT_ID = P.ID
AND P.GENOTYPE & C.GENOTYPE	= P.GENOTYPE	
ORDER BY ID ASC