-- 코드를 입력하세요
SELECT A_INS.ANIMAL_ID, A_INS.NAME
FROM ANIMAL_INS AS A_INS JOIN ANIMAL_OUTS AS A_OUTS
ON A_INS.ANIMAL_ID = A_OUTS.ANIMAL_ID
WHERE A_INS.DATETIME > A_OUTS.DATETIME
ORDER BY A_INS.DATETIME