-- 코드를 작성해주세요
-- BASS / SNAPPER 수 출력
-- 키 FISH_TYPE
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS FI JOIN FISH_NAME_INFO AS FNI 
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FISH_NAME IN ('BASS','SNAPPER')
