-- 코드를 입력하세요
-- 게시글.작성자.제목.가격.상태
SELECT BOARD_ID,WRITER_ID,TITLE,PRICE,
-- SALE = 판매중, RESERVED = 예약중, DONE = 거래완료
CASE WHEN STATUS = 'SALE' THEN '판매중' 
 WHEN STATUS = 'RESERVED' THEN '예약중' 
 WHEN STATUS = 'DONE' THEN '거래완료'
 END AS STATUS
 
FROM USED_GOODS_BOARD 
WHERE DATE(CREATED_DATE) = '2022-10-05'
ORDER BY BOARD_ID DESC