-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(B_S.SALES) AS TOTAL_SALES
FROM BOOK AS B JOIN BOOK_SALES AS B_S
ON B.BOOK_ID = B_S.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC

