-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, MAX(IFNULL(LENGTH, 10)) AS MAX_LENGTH, FISH_TYPE 
FROM FISH_INFO
GROUP BY FISH_TYPE
-- 평균 길이가 33CM 이상인 물고기
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE