-- 코드를 작성해주세요
-- 조건연산자 <> / != == '다르다'
SELECT CASE
WHEN SUM(
    CASE WHEN S.NAME = 'Python' THEN 1 ELSE 0 END
) > 0
    AND SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
    THEN 'A'
WHEN SUM(
    CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END
) > 0
    THEN 'B'
 WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
 THEN 'C'
 ELSE NULL
END AS GRADE,
ID, EMAIL
FROM DEVELOPERS AS D JOIN SKILLCODES AS S
ON D.SKILL_CODE & S.CODE != 0
GROUP BY ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID